pipeline {
    agent any
    
    stages {
        stage('Load Parameters') {
            steps {
                script {
                    def params = load './vars/parameters.groovy'
                }
            }
        }
        stage('Read Parameters') {
            steps {
                script {
                    params.name()
                }
            }
        }
    }
}
